# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
cache: packages
latex: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'
    packages:
      - librdf0-dev
      - libv8-dev
      - libjq-dev

script: 
## test that all .Rmd files can render 
  - R -e 'lapply(list.files(pattern=".*.Rmd", recursive=TRUE), rmarkdown::render)'
## Optionally test  
  - R -e 'lapply(list.files(pattern=".*.Rmd", recursive=TRUE), function(x) testthat::expect_length(lintr::lint(x),0))'


